version: "3.9"

services:
  backend:
    build: ./backend
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: react_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevents overwriting by host
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    command: npm run dev -- --host

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/app/backend
    depends_on:
      - frontend
      - backend
    restart: always

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: eiepims
      POSTGRES_USER: jud
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
